- docs/develop.md
- docs/forecasting.md
- docs/preprocessing.md
- functime/base/forecaster.py
- functime/conformal.py
- functime/conversion.py
- functime/cross_validation.py
- functime/evaluation.py
- functime/feature_extraction/calendar.py
- functime/forecasting/_ar.py
- functime/forecasting/_reduction.py
- functime/forecasting/elite.py
- functime/forecasting/naive.py
- functime/forecasting/snaive.py
- functime/metrics/multi_objective.py
- functime/metrics/point.py
- functime/plotting.py
- functime/preprocessing.py
- pyproject.toml
- tests/conftest.py
- tests/test_benchmarks.py
- tests/test_cross_validation.py
- tests/test_evaluation.py
- tests/test_fourier.py
- tests/test_preprocessing.py
- Rename all `groupby` to `group_by`
> build: Bump polars to 0.19.1.

- functime/feature_extraction/tsfresh.py
Improved perf for energy_ratio for Series and pl.Expr by about 50% each.
> perf: speed up energy_ratio

- functime/feature_extraction/tsfresh.py
Added some newlines so that docstrings are consistent in tsfresh.py
Removed the "Not Implemented" number_peaks for allowing pre-commit to function + compatibility with #55
> fix: Uniformize docstrings

- functime/feature_extraction/tsfresh.py
I fixed:
- return inline variable definition for: `approximate_entropies`, `autocorrelation`, `friedrich_coefficients`, `ratio_beyond_r_sigma` and `time_reversal_asymmetry_statistic`
- Used `extend` instead of `append` for `cwt_coefficients`
- Defined `_energy_ratio_series` which is used in `energy_ratio` in case of a series
- added safe guard to while loop in `lempel_ziv_complexity`
> fix: clean functions in tsfresh

- docs/ref/tsfresh.md
- functime/feature_extraction/tsfresh.py
- functime/ts_feature_library.py
- tests/test_tsfresh.py
1. Created FeatureLibrary. Once imported, users can now access pl.col("a").ts namespace for every feature that can be lazily generated.
2. Improved perf for has_duplicate_min/max by 10-20% by reducing some redundant computation.
3. Rewrote longest_strike_above/below_mean because ....max().fill_null() will not work when input is Series. When .max() is called, series input will result in a Python int result which does not have .fill_null()
4. Small docstring changes
@topher-lo
> TS Namespace + Small bug fixes + Reorg

- README.md
This should make it more clear that functime is about large panel datasets
> docs(readme): mention large panel datasets in headline

- docs/installation.md
- functime/forecasting/__init__.py
- pyproject.toml
Removes;
- pynndescent
- rich
Makes optional:
- plotly 
- kaleido
Resolves #81 #72
> build: Decrease core build size

- docs/forecasting.md
> docs(forecasting): fix wrong `roll` import

- functime/feature_extraction/tsfresh.py
- tests/test_tsfresh.py
Add ddof = 0 for `ratio_beyond_r_sigma`
Unittests for:
- ratio_beyond_r_sigma
- ratio_n_unique_to_length
- root_mean_square
> Unit tests

- .gitignore
- .pre-commit-config.yaml
- pyproject.toml
Update the gitignore to exclude rust files; also included some editor related stuff to avoid cluttering the repo.
> chore: Update gitignore, pyproject.toml and pre-commit config

- functime/plotting.py
Solves #83. Also forces plotly white theme on plots!
Is this plot enough, or should I add more?
I plan to add separate functions to rank series by CV (e.g. a scatterplot for CV and a rank_cv function as mentioned in #84).
> feat: add `plotting.plot_entities`

- functime/plotting.py
Make it so that all `plot_*` functions that require `y_true` can work with LazyFrames too.
Also place boundary checks on tuple unpacking of column names.
replaces #79
> feat(plotting): plot_* accept LazyFrames too

- Cargo.toml
- Makefile
- functime/__init__.py
- functime/_utils.py
- functime/feature_extraction/tsfresh.py
- src/feature_extraction/mod.rs
- src/lib.rs
1. Set up logging and "warning" infrastructure (using decorators)
2. Changed make
> feat: decorator logging infra

- pyproject.toml
Upgrade polars to 0.19.12 in pyproject.toml
> build: Bump polars to v0.19.12

- functime/feature_extractors.py
Minor update:
- add ratio_n_unique_to_length under our feature extraction namespace
> update: add ratio_n_unique_to_length in ts namespace

- functime/preprocessing.py
- pyproject.toml
1. Fixed trim
2. Made lag faster, removed fill_strategy option, added is_sorted option.
3. Bumped Polars version to 0.19.13 for faster join.
> fix!: Trim group by bug

- Cargo.toml
- functime/__init__.py
- functime/evaluation.py
- functime/feature_extractors.py
- functime/preprocessing.py
- pyproject.toml
1. Fixed some deprecated method names in feature_extractor
2. Updated versions
> fix: deprecated names and namespace import

- functime/backtesting.py
- functime/conversion.py
- functime/preprocessing.py
- tests/test_evaluation.py
Upgrades syntax to match our minimum supported polars version.
> style: run polars-upgrade

- Cargo.toml
- functime/__init__.py
- pyproject.toml
Bump the patch to pin Polars to <0.20
> Patch release to pin to polars<0.20

- .gitignore
- Cargo.toml
- functime/feature_extractors.py
- functime/preprocessing.py
- src/lib.rs
- src/preprocessing/fractional_differencing.rs
- src/preprocessing/mod.rs
The transformer implementation of frac diff was also replaced with the plugin implementation. The api did not change however.
Fractional differencing plugin
> feat(fractional_differencing): create frac diff plugin

- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- LICENSE
- README.md
- docs/code/feature_engineering.py
- docs/code/quickstart.py
- docs/develop.md
- docs/feature-extraction.md
- docs/forecasting.md
- docs/index.md
- docs/overrides/main.html
- functime/forecasting/automl.py
- mkdocs.yml
There are a few links that are either broken or lead to redirect. This PR tries to fix redirects.
I am unsure where to map broken links .
> patch redirect links

- docs/installation.md
- pyproject.toml
> docs: Expand installation details

- .pre-commit-config.yaml
Temporary removal until py3.8 support is dropped.
> ci: remove polars upgrade

- docs/notebooks/changepoint_detection.ipynb
- tests/test_changepoint_detection.py
- **test: replace with_row_count with with_row_index**
- **test: replace row_nr with index**
> test: Replace with_row_count with with_row_index

- functime/_plotting.py
- functime/plotting.py
- tests/test_plotting.py
Introduces a plotting utils module (location is not stable, but is a private module).
> refactor!: Change default arguments in plot_panel and refactor internals
