functime/feature_extraction/tsfresh.py
1. Do not approve for now.
2. Fixed a problem in benford_correlation. (x != "") is erroneous because x is numeric. In eager mode, np.corrcoef returns a matrix so we need to extract the coefficient, not return the whole matrix. Also, moving sort after value_counts which gives us another 3-5% perf improvment.
3. Significantly improved perf for permutation entropy by utilizing parallelism provided by pl.concat_list to a greater degree.
4. I have an idea to improve perf of binned_entropy. It is not implemented yet. I will likely work on this this weekend. It is tested on integers and works as fast as Tsfresh. I mentioned in a previous issue that we were about significantly slower and this could bring the performance to the same level. So this would be a big win. The only problem now I am …
=> fix+perf: Benford correlation and entropy features

functime/feature_extraction/tsfresh.py, pyproject.toml, tests/test_tsfresh.py
1. Fixed approximate_entropy. It works in eager mode now and is a lot faster than tsfresh
2. Reverted .count() back to .len(), because Series do not have .count(). I guess the 1-level of indirection is negligible.
3. Improved perf for absolute_maximum by 30-50%, and potentially lowered the memory usage by a lot. The is done by noticing that the max of abs(x) is either abs(x.max()) or abs(x.min()).  So we do not need to create an intermediate series x.abs(), which saves a lot of memory. The speed up also comes from the fact that we can use pl.max_horizontal to parallelize the computation for abs(x.max()) and abs(x.min()).
4. Fixed some test cases, but not all. Longest_strike's test cases are still failing. 
5. Added Heiner's change on mean_second_derivative_central which makes it work for …
=> fix: Approx. entropy in eager mode

functime/feature_extraction/tsfresh.py, tests/test_tsfresh.py
The issue is that in lazy Polars, slice behaves differently. The problem lies somewhere in its length calculation. Try running the following code, which will give us error in the lazy case. Since in our original code, we are just returning one expression at the end, the error didn't occur, but something inside was wrong. You can see the issue here: https://github.com/pola-rs/polars/issues/11594#issue-1931924184
```
df = pl.DataFrame({
"a": [1,2,1,2,1,2],
"b": [None, None, 1,1,1,1]
})
df.select(
pl.col("a").slice(offset = 0, length=pl.count() - 2).alias("1"),
pl.col("a").slice(offset = 1, length=pl.count() - 2).alias("2")
)
df.lazy().select(
pl.col("a").slice(offset = 0, length=pl.count() - 2).alias("1"),
pl.col("a").slice(offset = 1, length=pl.count() - 2).alias("2")
).collect()
```
I …
=> fixed autocorr + Lempel Ziv Complexity + Some failing tests

functime/feature_extraction/tsfresh.py, tests/test_tsfresh.py
Additional Features:
- range_over_mean: (max - min) / mean
- range_change: Returns the maximum value range. If percentage is true, will compute (max - min) / min, which only makes sense when x is always positive.
- longest_winning_streak: Returns the longest winning streak of the time series. A win is counted when (x_t+1 - x_t) >= 0
- longest_losing_streak: similar
- streak_length_stats: stats about the streaks.
- longest_streak_above: similar, but you supply the threshold
- longest_streak_below: similar, but you supply the threshold
- max_abs_change: Compute the maximum absolute change from X_t to X_t+1.
Other fixes:
1. Fixed a bug in energy_ratio pointed out by Mathieu
2. Changed "strike" to "streak" which is a more accurate English word
=> Additional Features, Fixed Energy Ratios

docs/forecasting.md
Fixes a small error where `X_splits` was never defined
=> docs(forecasting): fix variable name

functime/__init__.py, pyproject.toml
The version is only specified in `__init__.py` and is automatically fetched by setuptools, see [here](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata).
In other words: if this is merged, then we would have to change the version straight form `functime.__init__.py:__version__` and not from `pyproject.toml`.
Why would we want to approve this? So people can do `print(functime.__version__)` or - in other words - have a way to print functime's version from Python.
Closes #73.
=> refactor(version): add `__version__` to `__init__.py`

functime/feature_extraction/feature_extractor.py, functime/feature_extraction/tsfresh.py, functime/ts_feature_library.py, pyproject.toml, src/feature_extraction/feature_extractor.rs, src/feature_extraction/mod.rs, src/lib.rs, tests/test_tsfresh.py
Please do not approve until https://github.com/pola-rs/polars/issues/11736 is merged into main. Right now some unit tests are failing because of this issue.
1. Added unittests for all entropy features
2. Greatly improved perf for mean_change.
3. Improved Perf for time_reversal_asymmetry_statistic by reducing multiplications (but we need to do more additions). Multiplications are generally slower. This optimization only affects bigger time series.
4. Tuned absolute_energy in the eager case when time series is long, as NumPy's dot seems to outperform Polars's dot by a lot in that case.
5. Reverted the .cast() which was put there to avoid the issue mentioned above. Last checked the issue remains in 0.19.9.
6. Improved permutation entropy in the case tau = 1 by simplifying it a little bit. …
=> perf+test: More tsfresh updates

functime/feature_extraction/tsfresh.py, tests/test_tsfresh.py
- More optimizations for features that do not require NumPy / SciPy)
1. Benford Correlation is once again slightly faster now because I replaced value_counts by unique_counts. By putting pl.int_range(1, 10) in front, we do not need to sort, and unique_counts counts in the given order. In addition, unique counts is just slightly faster than value_counts because it only counts and does not return the corresponding values.
2. Number Crossing. Simplified the computation and got a significant speed boost.
3. percent_reoccurring_points,. Simplified the mathematical formula.
4. sum_reoccurring_values. The original one-line implementation was elegant, but is_unique, unique, and filter are more expensive. We can directly do a group_by (value_counts), which cuts down the size of the series, and …
=> perf: More tse optimisations

functime/preprocessing.py, tests/test_preprocessing.py
=> feat: fractional differencing function and test

data/m4_1d_train.parquet
Unfortunately the M4 data was [added to the repo](https://github.com/neocortexdb/functime/blob/d0f8918a64456ef1811e519fe9c0e302225e88c7/data/m4_1d_train.parquet) (not git LFS). This PR removes it from the repo and re-adds it as a git lfs pointer.
Still to do:
1. This does not remove that object from the git history - should use [git filter-repo](https://github.com/newren/git-filter-repo#how-do-i-use-it) to remove it.
2. We can configure a pre-commit builtin hook to avoid committing [files that are too big](https://github.com/pre-commit/pre-commit-hooks#check-added-large-files). Can do that in #108 too. If that's the case, we should agree on a filesize.
=> Restore M4 daily train data with git lfs

functime/feature_extractors.py
fix missing argument `q` for `index_mass_quantile` in the `ts` pl.Expr namespace
=> fix: missing arg ts namespace index mass quantile

functime/llm/common.py
The way to call the OpenAI python API has changed since the original functime LLM code was written.
If you try to use LLM now, it does nothing and says that you need to downgrade your version of the openai library to use the library.
We could alternatively enforce that the functime[llm] addon has a compatible version of openai, but I don't think it is desirable to keep an outdated version of the library when upgrading the code is so easy.
I have made some changes which fix the issue. 
These are fairly superficial.
I haven't written any tests for this, which would need some good mocks, etc. 
I 'tested' this by running the llm.iypnb notebook.
This is fixing breaking issues.
=> fix: update api call to current openai python format

.pre-commit-config.yaml
Implements Marco Gorelli's excellent [polars-upgrade](https://github.com/MarcoGorelli/polars-upgrade) to always use the latest Polars syntax.
Given the frequency of the releases, this could be of great help.
=> Add polars-upgrade pre-commit hook

mkdocs.yml
Rename `ref/feature-extraction.md` into `ref/feature-extractors.md` in mkdocs configurations.
=> Fix filename in API reference

docs/forecasting.md, docs/index.md, docs/notebooks/benchmarks.ipynb, functime/base/forecaster.py, functime/base/metric.py, functime/forecasting/lance.py, functime/preprocessing.py, tests/test_preprocessing.py, tests/test_tsfresh.py
Typos in both codebase and docs
=> patch: fix typos

functime/feature_extractors.py, pyproject.toml
`bottleneck` is listed as dependency but used nowhere.
=> build: remove bottleneck

pyproject.toml, tests/test_evaluation.py, tests/test_forecasting.py, tests/test_preprocessing.py
Ignoring a set of slow tests by default and some other small cleanup
=> remove unnecessary tests

functime/ranges.py
Uses the appropriate Polars type alias `TimeUnit`.
=> refactor(ranges): use appropriate Polars type aliases

functime/cross_validation.py, tests/test_cross_validation.py
This is a first draft of how I would address and fix #167 to add support for float in `train_test_split`.
I noticed typing has some issues but it is already been addresses in #161.
Question: Would you like to have a default value (e.g. 25% as in scikit-learn) for the test size?
=> Add float support in `train_test_split`

functime/preprocessing.py
Fixes #182 
Correcting the typo to avoid NameError when using fill_strategy in the roll function
=> fix: variable name typo in roll fill_strategy

pyproject.toml
Otherwise some fixtures fail (e.g. pl.from_pandas)
=> build: add pyarrow as a test dependency

CONTRIBUTING.md
Adding a draft for CONTRIBUTING.md. Would like to ask for a review to @ngriffiths13, @FBruzzesi, @miroslaavi who is working on a PR and installed the project locally, and also @ rodrigogiraoserrao because he says they are important (🤪).
=> chore: add CONTRIBUTING.md draft

docs/ref/forecasting.md
Just fixed a typo in `docs/ref/forecasting.md`.
=> docs: Fix typo in docs/ref/forecasting.md

functime/plotting.py, tests/test_plotting.py
Fixes #179 
This pull request introduces a new function _set_subplot_default_kwargs to dynamically set default plot sizes for subplots, enhancing the readability and aesthetics of plots in the plotting module. This function is now utilized in plot_panel, plot_forecasts, and plot_backtests to ensure consistent and optimal sizing of plots, especially when the user hasn't specified height and width in kwargs.
Additionally, this PR includes a fix for the #179 for the subplot functions plot_forecast, plot_panel, and plot_backtests.
Also, added a logic if n_series is greater than the max unique entities, then use max unique entities instead for plotting to avoid an error.
=> refactor: Subplot layout adjustments

functime/feature_extractors.py, tests/test_feature_extractors.py
Closes #206
- `cwt_coefficients` does not throw `ValueError` anymore.
- Now there is a minimal unit test for `cwt_coefficients`.
I am not 100% sure in the fix myself. I have compared with https://github.com/scipy/scipy/blob/v1.13.0/scipy/signal/_wavelets.py#L543 and with https://tsfresh.readthedocs.io/en/latest/_modules/tsfresh/feature_extraction/feature_calculators.html#cwt_coefficients. But I do not have time to validate the math with the code. I will need a very thorough review.
=> fix(206): Fix `ValueError` in `cwt_coefficients`

functime/cross_validation.py, functime/feature_extractors.py, functime/type_aliases.py
This has been bugging me for a while. Though I can't get rid of one error:
@FBruzzesi have any ideas? (Taking the liberty to tag @marcogorelli too, whom I know hates function overloads)
=> refactor: Properly annotate `train_test_split`

functime/cross_validation.py, functime/feature_extractors.py, functime/plotting.py, functime/preprocessing.py, tests/conftest.py, tests/test_benchmarks.py, tests/test_cross_validation.py
- **refactor(internals): replace pl.count() with pl.len()**
- **style: format spaces**
=> refactor: Replace pl.count() with pl.len()

functime/base/model.py
Should finalise full compatibility with polars 0.20.7
=> refactor: use replace over map_dict

pyproject.toml
This fixes several instances of the following errors. Out of good measure, I guess it's safe to just bump the min version since we're going to drop support for the older versions of polars.
=> build: Bump to polars version 20.8

pyproject.toml
Because benchmark dependencies made it impossible to install on py3.12!
=> build: reorder dependency groups
